name: Python Pipeline for CI and CD

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@4
      - name: Setup Python
        uses: actions/setup-python@v1.1.1
      - name: Run python script
        run: python hello.py 

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@4
      - uses: actions/upload-artifact@v4
        with:
          name : hello
          path: .
